kodealabs_test/kodealabs_test/urls.py
from django.contrib import admin
from django.urls import path, include
from flights.views import ItinerariesListView, LegListView, FetchFlights

urlpatterns = [
    path('admin/flights/itinerarie/list/', ItinerariesListView.as_view(), name='itinerarie-list'),
    path('admin/flights/leg/list/', LegListView.as_view(), name='leg-list'),
    path('admin/', admin.site.urls),
    path('', FetchFlights.as_view(), name='home'),
]

kodealabs_test/flights/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _  


class Leg(models.Model):
    id = models.CharField(_("id"), max_length=10, primary_key=True)
    departure_airport = models.CharField(_("Departure airport"), max_length=3)
    arrival_airport = models.CharField(_("Arrival airport"), max_length=3)
    departure_time = models.DateTimeField(_("Departure time"))
    arrival_time = models.DateTimeField(_("Arrival time"))
    stops = models.IntegerField(_("Stops"))
    airline_name = models.CharField(_("Airline name"), max_length=50)
    airline_id = models.CharField(_("Airline ID"), max_length=2)
    duration_mins = models.IntegerField(_("Duration mins"))


class Itinerarie(models.Model):
    id = models.CharField(_("id"), max_length=10, primary_key=True)
    legs = models.ManyToManyField(Leg, verbose_name=_("Legs"))
    price = models.FloatField(_("Price"))
    agent = models.CharField(_("Agent"), max_length=50)
    agent_rating = models.FloatField(_("Agent rating"))

kodealabs_test/flights/views.py
from django.shortcuts import render
from django.views.generic import View, ListView
from .models import Itinerarie, Leg
import requests


class FetchFlights(View):
    def get(self, request):
        try: 
            response = requests.get('https://raw.githubusercontent.com/Skyscanner/full-stack-recruitment-test/main/public/flights.json')
            data = response.json()

            for l in data['legs']:
                leg = Leg.objects.get_or_create(
                    id = l['id'],
                    departure_airport = l['departure_airport'],
                    arrival_airport = l['arrival_airport'],
                    departure_time = l['departure_time'],
                    arrival_time = l['arrival_time'],
                    stops = l['stops'],
                    airline_name = l['airline_name'],
                    airline_id = l['airline_id'],
                    duration_mins = l['duration_mins'],
                )
           
            
            for i in data['itineraries']:
                itinerarie = Itinerarie.objects.get_or_create(
                    id = i['id'],
                    price = i['price'].split('£')[1],
                    agent = i['agent'],
                    agent_rating = i['agent_rating'],
                )

                for leg in list(i['legs']):
                    itinerarie[0].legs.add(Leg.objects.get(id=leg))
                    itinerarie[0].save()

        except:
            return render(request, 'flights/error.html')

        return render(request, 'flights/success.html')


class ItinerariesListView(ListView):
    model = Itinerarie
    template_name = "flights/itineraries_list.html"

    def get_queryset(self):
        itineraries = Itinerarie.objects.all()
        try:
            price = self.request.GET['price']
            itineraries = itineraries.filter(price__lte=price)
        except: pass
        try:
            rating = self.request.GET['rating']
            itineraries = itineraries.filter(agent_rating__gte=rating)
        except: pass

        return itineraries
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            price = self.request.GET['price']
            context["price"] = price
        except: pass
        try:
            rating = self.request.GET['rating']
            context["rating"] = rating
        except: pass

        return context
    

class LegListView(ListView):
    model = Leg
    template_name = "flights/leg_list.html"

    def get_queryset(self):
        legs = Leg.objects.all()
        try:
            airline_name = self.request.GET['airline_name']
            legs = legs.filter(airline_name__contains=airline_name)
        except: pass

        return legs
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            airline_name = self.request.GET['airline_name']
            context["airline_name"] = airline_name
        except: pass

        return context
    

kodealabs_test/flights/templates/flights/error.html
<style>
    * {
        box-sizing: border-box;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }
    body {
        margin: 0;
        padding: 1rem;
    }
    p {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 1rem;
        border-radius: 4px;
        font-size: 0.8125rem;
    }
    a {
        display: block;
        margin-bottom: 0.25rem;
        font-size: 0.75rem;
    }
</style>

<p>Error al cargar elementos.</p>
<a href="../../admin">Volver a la página de administrador</a>
<a href="{% url 'itinerarie-list' %}">Itinerarios</a>
<a href="{% url 'leg-list' %}">Tramos</a>

kodealabs_test/flights/templates/flights/itinerarie_list.html
<style>
    * {
        box-sizing: border-box;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }
    body {
        margin: 0;
    }
    .page {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 1rem;
    }
    form {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 0.5rem;
        border-radius: 4px;
    }
    label {
        font-size: 0.8125rem;
    }
    input {
        border: 1px solid rgba(0, 0, 0, 0.5);
        border-radius: 2px;
        padding: 0.25rem;
        width: 150px;
    }
    form {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }
    button {
        width: fit-content;
        padding: 0.25rem 1rem;
        background-color: black;
        color: white;
        font-weight: 500;
        font-size: 0.75rem;
        border-radius: 2px;
        cursor: pointer;
    }
    .itinerarie {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 1rem;
        margin-bottom: 1rem;
        p {
            font-size: 0.75rem;
        }
    }
    h4 {
        margin: 0;
    }
    .leg {
        margin-bottom: 2rem;
    }
    a {
        display: block;
        margin-bottom: 0.25rem;
        font-size: 0.75rem;
    }
    
</style>
<div class="page">
    <a href="{% url 'home' %}">Inicio</a>
    <a href="{% url 'itinerarie-list' %}">Itinerarios</a>
    <a href="{% url 'leg-list' %}">Tramos</a>
    <h3>Itinerarios</h3>
    <form action="" method="get" >
        <div class="input-field">
            <label for="id_price">Precio menor a:</label>
            <input type="number" name="price" id="id_price" value="{{ price }}" min="0">
        </div>
        <div class="input-field">
            <label for="id_rating">Calificación mayor a:</label>
            <input type="number" step=".1" name="rating" id="id_rating" value="{{ rating }}" min="0" max="10">
        </div>
        
        <button>Buscar</button>
    </form>
    
    {% for itinerarie in itinerarie_list %}
        <div class="itinerarie">
            <h4>Itinerario {{ itinerarie.id }}</h4>
            <h5><b>Tramos: </b></h5>
            {% for leg in itinerarie.legs.all %}
            <div class="leg">
                <p>- {{ leg.id }}</p>
                <p><b>Aeropuerto de salida: </b>{{ leg.departure_airport }}</p>
                <p><b>Aeropuerto de entrada: </b>{{ leg.arrival_airport }}</p>
                <p><b>Hora de salida: </b>{{ leg.departure_time|date:"d/m/Y h:i a" }}</p>
                <p><b>Hora de llegada: </b>{{ leg.arrival_time|date:"d/m/Y h:i a" }}</p>
            </div>
            {% endfor %}
            <p><b>Precio: </b>{{ itinerarie.price }}</p>
            <p><b>Agente: </b>{{ itinerarie.agent }}</p>
            <p><b>Calificación: </b>{{ itinerarie.agent_rating }}</p>
        </div>
    {% empty %}
    <p>No se encontraron resultados</p>
    {% endfor %}
</div>

kodealabs_test/flights/templates/flights/leg_list.html
<style>
    * {
        box-sizing: border-box;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }
    body {
        margin: 0;
    }
    .page {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 1rem;
    }
    form {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 0.5rem;
        border-radius: 4px;
    }
    label {
        font-size: 0.8125rem;
    }
    input {
        border: 1px solid rgba(0, 0, 0, 0.5);
        border-radius: 2px;
        padding: 0.25rem;
        width: 150px;
    }
    form {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }
    button {
        width: fit-content;
        padding: 0.25rem 1rem;
        background-color: black;
        color: white;
        font-weight: 500;
        font-size: 0.75rem;
        border-radius: 2px;
        cursor: pointer;
    }
    .leg {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 1rem;
        margin-bottom: 1rem;
        p {
            font-size: 0.75rem;
        }
    }
    h4 {
        margin: 0;
    }
    a {
        display: block;
        margin-bottom: 0.25rem;
        font-size: 0.75rem;
    }
</style>

<div class="page">
    <a href="{% url 'home' %}">Inicio</a>
    <a href="{% url 'itinerarie-list' %}">Itinerarios</a>
    <a href="{% url 'leg-list' %}">Tramos</a>
    <h3>Tramos</h3>
    <form action="" method="get">
        <div class="input-field">
            <label for="id_airline_name">Aerolína</label>
            <input type="text" name="airline_name" id="id_airline_name" value="{{ airline_name }}">
        </div>
        <button>Buscar</button>
    </form>
    
    {% for leg in leg_list %}
        <div class="leg">
            <h4>Tramo {{ leg.id }}</h4>
            <p><b>Aeropuerto de salida: </b>{{ leg.departure_airport }}</p>
            <p><b>Aeropuerto de entrada: </b>{{ leg.arrival_airport }}</p>
            <p><b>Hora de salida: </b>{{ leg.departure_time|date:"d/m/Y h:i a" }}</p>
            <p><b>Hora de llegada: </b>{{ leg.arrival_time|date:"d/m/Y h:i a" }}</p>
            <p><b>Paradas: </b>{{ leg.stops }}</p>
            <p><b>Nombre de aerolínea: </b>{{ leg.airline_name }}</p>
            <p><b>ID aerolínea: </b>{{ leg.airline_id }}</p>
            <p><b>Duración: </b>{{ leg.duration_mins }} minutos</p>
        </div>
    {% empty %}
    <p>No se encontraron resultados</p>
    {% endfor %}
</div>

kodealabs_test/flights/templates/flights/success.html
<style>
    * {
        box-sizing: border-box;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }
    body {
        margin: 0;
        padding: 1rem;
    }
    p {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 1rem;
        border-radius: 4px;
        font-size: 0.8125rem;
    }
    a {
        display: block;
        margin-bottom: 0.25rem;
        font-size: 0.75rem;
    }
</style>

<p>Elementos cargados con éxito.</p>
<a href="../../admin">Ir a la página de administrador</a>
<a href="{% url 'itinerarie-list' %}">Itinerarios</a>
<a href="{% url 'leg-list' %}">Tramos</a>